# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    if not bld.env['ENABLE_EXAMPLES']:
        return;

    obj = bld.create_ns3_program('leo-circular-orbit-trace',
                                 ['core', 'leo', 'mobility'])
    obj.source = 'leo-circular-orbit-tracing-example.cc'

